### ISSUE TITLE
Sometimes page with specific bounty does not load correctly

### ISSUE THREAD

**Issue by Rassl** [stakwork/sphinx-tribes#765] opened 2023-09-29 18:03 UTC
**As is**: when user tries to navigate with link to specific bounty, for example: https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696010046, page is not loading correctly: 
<img width="1376" alt="image" src="https://github.com/stakwork/sphinx-tribes/assets/8904434/2f1d292c-2527-48fc-b527-51b799788eee">

**To be**: page is loaded and filled with data

**Comment by ecurrencyhodler** [comment] 2023-09-29 18:53
Thanks for reporting this. This might be tricky to solve because I can't reliably reproduce this but I have seen this occur several times. 

The situation where I have the greatest success of reproducing this bug is when I click on a link for the first time and am directed to that url in a separate tab.

**Comment by ecurrencyhodler** [comment] 2023-10-12 18:33
This has been resolved by #793

**Closed by ecurrencyhodler** 2023-10-12 18:33 UTC
Labels: bug, bounties
